#!/bin/sh -e

set -e

APPLICATION="${0##*/}"

USAGE="$APPLICATION [options]
Wraps enter-chroot to start a Cinnamon session.
By default, it will log into the primary user on the first chroot found.
Options are directly passed to enter-chroot; run enter-chroot to list them."

exec sh -e "`dirname "\`readlink -f -- "$0"\`"`/enter-chroot" "$@" xinit /usr/bin/mate-session
