#!/bin/sh -e
# Copyright (c) 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='mate'
DESCRIPTION='Installs MATE along with common applications. (Approx. 800MB)'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install ubuntu=ubuntu-mate-desktop,task-mate-desktop -- network-manager
