#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the Xfce desktop environment. (Approx. 250MB)'
HOSTBIN='startmate'
CHROOTBIN='crouton-noroot startmate'
. "${TARGETSDIR:="$PWD"}/common"



install mate-desktop dbus-x11 ubuntu=shimmer-themes, \
        -- hddtemp xorg

TIPS="$TIPS
You can start MATE via the startmate host command: sudo startmate
"
